### ISSUE TITLE
A few comments from alpha-testing

### ISSUE THREAD

**Issue by JesperWe** [notum-cz/strapi-plugin-content-versioning#1]
### Describe the bug

Hello! I hope you don't mind an issue for this not yet released plugin. Consider it an Alpha QA report :-)
I am very keen on this project, so I have done a bit of testing and just wanted to let you know the experience.

### Observations for plugin v0.1.4

1. When saving new versions the `created_by_id` and `updated_by_id` columns in DB are not set.
2. The patch file references the Sentry plugin. So it needs to be installed. Mention in readme?
3. The line `"postinstall": "patch-package",` is needed in `package.json`. Mention in readme?

### System

- Node.js version: v16
- Strapi version: v4.0.6
- Database: Postgres
- Operating system: MacOS

**Comment by martincapek** [comment]
Hi, at first, thank a lot for testing! 

For your observations.

1) I tried it on fresh install and you are right I will release patch till end of the week
2) We are currently working or rewriting readme and it will be released today, also I misscopied file and it should be `@strapi+admin+4.0.2.patch` not @strapi/sentry
3) This is also added in readme update, it's best to set it before install and then run npm install or yarn so it runs postinstall as well and apply that patches
