### ISSUE TITLE
New version removed all relational fields data when clicked on strapi save

### ISSUE THREAD

**Issue by hafizasadabbas** [notum-cz/strapi-plugin-content-versioning#110]
### Steps to reproduce the behavior

1. Go to 'Any article
2. Click on the ' Strapi Save button
3. Scroll down to 'any Relational field'
4. field's selected data has been removed.

### Expected behavior

It should work as a versioning plugin save button.

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v16
- NPM version:
- Strapi version: 4.9.0
- Database: postgres
- Operating system: MacOS
- notum-cz/strapi-plugin-content-versioning: 0.4.8

**Comment by omikulcik** [comment]
Hi @hafizasadabbas, as menitoned in the readme this plugin does not work with relations. We will be adding that feature but it does not work at the moment.
