### ISSUE TITLE
Internationalized content

### ISSUE THREAD

**Issue by codrin-iftimie** [notum-cz/strapi-plugin-content-versioning#12]
### Describe the bug

The plugin does not work well with internationalized content.

### Steps to reproduce the behavior

1. Create a Collection type (eg: LandingPage)
2. Enable i18n for it
3. Translate the content of a entry (LandingPage)
4. Install the plugin and enable it
5. Navigate to the listing of landing pages
6. You can't see your entry

### Expected behavior

I should be able to see the entry I created. Also noticed one bug if I create a new entry and add a translation for it, then the publish button will unpublish the English version (initial translation)

### System

- Node.js version: v16.14.0
- NPM version:6.14.16
- Strapi version: v4
- Database: filebased (default)
- Operating system: Linux pop-os 5.15.15-76051515-generic

### Additional context

Fill in from another locale is also not working correctly. I'm guessing the internationalization part does not play well with the versioning schema.

**Comment by martincapek** [comment]
Hello, thanks for report. I will look at it and let you know when we fix it.

**Comment by meganoob1337** [comment]
I had a similar problem when i tried the plugin with internationalized content.
The Feature/Fix would be great for us aswell, as we need some kind of content versioning, but since we have i18n it is not viable.

**Comment by meganoob1337** [comment]
@martincapek  is there any update if this is going to be looked at in the near Future? 
I sadly have too little experience with plugin development to pin down the problem or a solution

**Comment by baptiste-bellot** [comment]
Hello @martincapek,

Facing the same problem with i18n support as a requirement for my project I created a fork of the plugin where I made this work. It might not be a perfect solution but maybe this can be of some interest for you, [see the fork](https://github.com/baptiste-bellot/strapi-plugin-content-versioning/tree/i18n-compatibility-workaround)

**Comment by martincapek** [comment]
Hi @baptiste-bellot , Im currently working on it  so thanks for it! I will look at it :)

**Comment by lundcm** [comment]
@martincapek where did that work end up? We need internationalization as well and would be willing to pick up where you left off. Thanks!

**Comment by martincapek** [comment]
Hi @lundcm we can schedule meeting with @ondrej-janosik and discuss it :) please contact me on martin.capek@notum.cz

**Comment by tasola** [comment]
Hi @martincapek & @lundcm! What is the status on this feature? We're also highly interested in having it.

**Comment by meganoob1337** [comment]
@tasola https://feedback.strapi.io/customization/p/q1-2023-draft-publish-v2
Maybe this will meet your usecase once its ready, this is our hope as well :)

**Comment by martincapek** [comment]
Hi @tasola here is the draft PR, we will test it and I let you know https://github.com/notum-cz/strapi-plugin-content-versioning/pull/47

**Comment by tasola** [comment]
@meganoob1337 thanks for the insight, I've missed that on the feedback forum! However, that doesn't look like it will have the possibility to switch between historical versions, right? Good to see they're working on it though!

**Comment by tasola** [comment]
@martincapek Oh awesome, thank you! Fingers crossed the testing goes smooth!

**Comment by tasola** [comment]
@martincapek any news on the testing? :)

**Comment by martincapek** [comment]
Hi all, beta is released. Can you please take a look that everything is fine? If yes we will release it as stable version. 

Big thanks!

https://www.npmjs.com/package/@notum-cz/strapi-plugin-content-versioning/v/1.0.0-beta.0

**Comment by mjadczuk** [comment]
@Fikoun @martincapek Outside of installing 1.0.0 beta release and using the new patch, is there anything I need to do to enable i18n? I'm still having problems with saving content in another locale. Despite choosing a different locale in the right side panel, it saves everything under the default locale. I do have a relation in one of the models though, but I can confirm the same issue persists in localized content types without any relations.

**Comment by martincapek** [comment]
No that sould be ok. Can you provide repository or something? I was tried it on new install and update and both works correctly.

**Comment by mjadczuk** [comment]
@martincapek I cannot provide you access to the repository, but if you're saying it should just work out of the box, I guess I'll try to recreate the project and move the sources there step by step to see if I can get the versioning to work. If I'll manage to recreate the issue, I'll let you know.

**Comment by tasola** [comment]
@mjadczuk I forgot to rebuild the project after downloading `1.0.0-beta.0`, and got the same behaviour as you. Maybe you forgot that step as well?

**Comment by mjadczuk** [comment]
I've rebuilt the project, removed DB volume locally, as well as caches and Strapi config (with admin panel setup). The issue still persists. Instead of saving the entry as a localized version of a specific component, it adds another instance of the component with the default locale selected. I've tried pinpointing which extension or functionality could cause this, but I wasn't able to yet.

**Comment by tasola** [comment]
I think I experience the same thing now (without having changed anything, just editing entries)...

When I create a new locale on entry X and "save new version" (without hitting the Strapi native "Save" first), the version first appears to be saved to the default locale. When you go back to the list view of entries however, that version is saved as a totally new entry (with default locale). It is not present in either locales on the original entry X. The new locale on X is empty.

When I create a new locale on entry X and hit Strapi's native "Save", and then hit "save new version", the version again first appears to be saved to the default locale. When you go back to the list view of entries, you can see that a new locale has been added on X though. When you re-enter X and go to the new locale, the locale is properly set.

Could there be some kind of database bug causing this? I can try to reset my db and see if the issue persists.

Should we report this as a new issue @martincapek ?

**Comment by tasola** [comment]
Same thing when I reset my database

**Comment by tasola** [comment]
This seems to be because the new locale version gets another `vuid` than the original entry with the default locale. Any idea how this can happen? It's not the same in my hosted environment (which reflects how it worked when I first tested out this patch)...
