### ISSUE TITLE
Doesn't work with Unique fields

### ISSUE THREAD

**Issue by sanjayteel** [notum-cz/strapi-plugin-content-versioning#120]
We have courses which have slug and batches as unique fields. When we try to save a version, it results in error because of these 2 fields.
![validation-error](https://github.com/notum-cz/strapi-plugin-content-versioning/assets/140395519/a3ae77c3-dbbc-4fef-b259-6e59ea8ebd74)

Hoping for a quick support here.

Thanks

**Comment by omikulcik** [comment]
Hello, this is a known limitation of this plugin. Unfortunately, as it is written in the read me, unique fields do not work with this plugin at the moment.

**Comment by sanjayteel** [comment]
Hi @omikulcik , 

How can I undo "Override the Save Button functionality"? And are you guys planning to come with a solution for unique fields and relations?

**Comment by omikulcik** [comment]
Hi @sanjayteel, just removing the patch from the /patches directory and reinstalling node modules should do it. Yes, we are. The relations support is nearly finished. Supporting unique fields is on our roadmap but it will take some time.

**Comment by sanjayteel** [comment]
Hi @omikulcik can you please update the timeline. Its, quite important for us to plan our development accordingly.

Regards, 
Sanjay

**Comment by omikulcik** [comment]
@omikulcik I will but it is only rough estimates because we have projects for our clients and maintaining plugins is lower priority.

**Comment by sanjayteel** [comment]
Hi @omikulcik , it will be ok even if you share the rough estimate for both the tasks as I will be able to share that with my team and we will be able to plan accordingly.

Regards, 
Sanjay
