### ISSUE TITLE
Patch version for 4.13.2 is needed

### ISSUE THREAD

**Issue by arnovanstaden** [notum-cz/strapi-plugin-content-versioning#123]
### Describe the bug

No patch for version for 4.13.2.

Thanks in advance

**Comment by omikulcik** [comment]
Hi @arnovanstaden, I will do my best to create the patch.

**Comment by omikulcik** [comment]
I have created a patch for v 4.13.3 in #124 . It should be the same as for 4.13.2. Just rename the file.

**Comment by arnovanstaden** [comment]
Thanks for the help Ondrej!
