### ISSUE TITLE
Deleting a version navigates to the home page instead of staying on the current model's page

### ISSUE THREAD

**Issue by ruinixu** [notum-cz/strapi-plugin-content-versioning#145]
### Describe the bug

When deleting a version from a Single type, I am taken back to the Strapi homepage, instead of staying on the same page for the single type. This does not happen to Collection types.

### Steps to reproduce the behavior

1. Go to a Single type on the content editor (ex. HomePage)
2. Click on a draft version you would like to delete
3. Click 'Delete this entry' then 'Confirm'
4. Get navigated back to the Strapi Admin Home page.

### Expected behavior

1. Go to a Single type on the content editor (ex. HomePage)
2. Click on a draft version you would like to delete
3. Click 'Delete this entry' then 'Confirm'
4. Remain on the same page, but viewing the published version now(default view when clicking on an entry)

### System

- Node.js version: v18.18.2
- NPM version: v9.8.1
- Strapi version: ^4.14.5
- Database: Postgres
- Operating system: Ubuntu 22.04.3 LTS (GNU/Linux 6.2.0-1014-aws x86_64)

**Comment by omikulcik** [comment]
Hi @ruinixu, thank you for reporting this issue! 

single types are currently not supported but it is on the roadmap. It might somehow work but proceed with caution. I will close this in favor of grouping similar information under #133. In case you encounter more problems with single types, please drop a comment in the mentioned issue. It will be very helpful once we start working on it.
