### ISSUE TITLE
Versioning of collection type doesn't work properly when collection has relation to other collection

### ISSUE THREAD

**Issue by vovapankiw** [notum-cz/strapi-plugin-content-versioning#148]
### Describe the bug

Creating a new version of Collection that has related Collection as a field is not saved properly.

### Steps to reproduce the behavior

1. Go to Content-Type-Builder and create two collection types:

-     Restaurant:
       title: short text field
       versioning enabled
-     Type
      type: short text field
      relation field with Restaurant Many-to-Many
      versioning disabled
2. Go to Content Manager and create:
- 2 Types:  
  type: FastFood, relation field: empty => Save and Publish
  type: Cafe, relation field: empty => Save and Publish
- 1 Restaurant:
  title: Friends
  types(relation field): FastFood => Save and Publish
4. V1 of Friends restaurant collection is created
5. Change types(relation field) to Cafe instead of FastFood => Save and Publish
6. Refresh the page or go back to collections and enter created collections again
7. V2 of Friends restaurant collection is created, but the types field includes both FastFood and Cafe relation

### Expected behavior

A new version of content should save the current state of relation fields

### Code snippets

https://github.com/vovapankiw/strapi-versioning/tree/main

### System

- Node.js version: v18.16.0
- NPM version: v9.5.1
- Strapi version: 4.14.4
- Database: sqllite/postgres
- Operating system: Windows

**Comment by omikulcik** [comment]
Hey @vovapankiw, this should be supported already but maybe there is some bug in the code. I will try to replicate it and get back to you.

**Comment by omikulcik** [comment]
@vovapankiw I have exactly replicated the steps that you provided and everything worked fine for me. Please, are on the latest version of the plugin? Thank you! :)
<img width="713" alt="image" src="https://github.com/notum-cz/strapi-plugin-content-versioning/assets/44231035/9a886f7b-e6de-4f95-8884-a9fd2e2163a8">

**Comment by vovapankiw** [comment]
Thanks @omikulcik for so fast response, really appreciate it!
I am using the last version of the plugin: "@notum-cz/strapi-plugin-content-versioning": "^1.1.5".
I added just one more step, after you changed a relation in step 5, refresh the page to see if it is correctly saved in DB
Because in my case, I have the next view after refresh:
![image](https://github.com/notum-cz/strapi-plugin-content-versioning/assets/40857607/db1153e7-bfcd-44c7-b68d-1b947c2d6822)
And in database it is also saved as two relations connected to a new version with id 2.
![image](https://github.com/notum-cz/strapi-plugin-content-versioning/assets/40857607/a21b6417-6303-4a0e-842f-b2287c6e3d49)
And initial (was created after V1 was published) record is removed
![image](https://github.com/notum-cz/strapi-plugin-content-versioning/assets/40857607/fc5a820f-fbfe-4aea-a1ea-9d78ad1fbe8d)

**Comment by omikulcik** [comment]
Hi @vovapankiw, sorry for late response. I was on vacation last week. Now that I refreshed the page I can confirm this bug also happens to me. I will try to figure out a fix.

**Comment by omikulcik** [comment]
@vovapankiw I have proposed a fix in #151. Will just wait until my colleague reviews it and we will ship it.
