### ISSUE TITLE
Upon saving the the post is marked as unpublished.

### ISSUE THREAD

**Issue by bobbylipps** [notum-cz/strapi-plugin-content-versioning#149]
When I save a page it gets changed to unpublished. Users forget to publish and the page will no longer be visible.

### Steps to reproduce the behavior
Edit a page/post and save it. It will be marked as unpublished.

### Expected behavior
I believe the page should be stay on the current status(published/unpublished) when saved.

### Additional context
If this is intentional behavior for the plugin is there a way for me to change this?

**Comment by omikulcik** [comment]
Hi @bobbylipps, thank you for your feedback. Nonetheless, I believe the current behaviour is correct. When you hit the Save button a new version of the content is created and you may not want it to be instantly published. Instead the previously published remains published and as soon as you have next version ready to be published you can do so. This enables you to have multiple draft versions which is in my point of view great feature to have.
