### ISSUE TITLE
Validation running on draft entries

### ISSUE THREAD

**Issue by AdrianFahrbach** [notum-cz/strapi-plugin-content-versioning#159]
### Describe the bug

The plugins run the validation on draft articles, even though Strapi by default does not do that.
This means that I cannot create new versions of unfinished entries. i have to fill out all required fields even if the entry is still a draft and has not been published yet.

### Steps to reproduce the behavior

1. Create a collection with required fields.
2. Create a new entry where at least one of the required fields is empty. Strapi creates that entry successfully.
3. Do a change to that new article, still leaving one of the required fields empty. Strapi will throw a 500 error and the error message will contain a validation error.

### Expected behavior

I should be able to create unfinished versions of drafts. The validation should only run on published entries.

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v18.19.0
- Strapi version: v4.15.5
- Database: Postgres
- Operating system: MacOS
- Plugin version: v1.2.6

### Additional context

Here is a video showing the issue.
In that video we have two different Strapi instances. The white one is running without the plugin and therefore represent the default Strapi behaviour. The dark Admin Panel is a Strapi instance running with the plugin enabled.

In the video I create a new news-article. The news-article has multiple required fields. I intentionally do not fill out the teaser field, even though it is required. The required star is missing in the white instance, thats a bug in our custom field. It is required.
After creating the new entry I try to do a change to it. The regular Strapi (white) saves that successfully. The Strapi instance with the plugin enabled (dark) does not save the change because it can't create a new version. My screen switches to my running VSCode debugger that shows where the error is thrown. It is a validation error that says that the teaser field should have a string value even though my entry is a draft.

https://github.com/notum-cz/strapi-plugin-content-versioning/assets/45072099/6e234081-f27a-45ec-8efb-74d7be39cfd1

**Comment by omikulcik** [comment]
Hi @AdrianFahrbach, thank you for a thorough description of the bug. Seems strange. I will try it myself and see what can I do about it. Will get back to you by the end of the week.

**Comment by AdrianFahrbach** [comment]
@omikulcik Thank you very much! Let me know if you got problems reproducing this. If yes, then I can dig deeper into our code and see if this is caused by us although it doesn't seem like that right now.

**Comment by omikulcik** [comment]
@AdrianFahrbach It seems I found a solution. The only caviat is that when you have already published version and you save it with a required field empty it wont save it because the validation is on front-end. However, there is a workaround to unpublish the version -> create new one -> publish back the old one.
