### ISSUE TITLE
Deadlock crash when updating an entity with many to many relationship

### ISSUE THREAD

**Issue by rtaieb** [notum-cz/strapi-plugin-content-versioning#164]
### Deadlock crash when updating an entity with many to many relationship

Hi,

When there is a many to many relationship between two collections, publishing a new version of an entity of one of them make the server crashes with an error code 40P01 , and deadlock in DB error message.

### Steps to reproduce the behavior

1. Create two entities "test1" and "test2" with both "draft/published" and "content versioning" enabled
2. For both of them, create a "title" text field, and a many to many relation field between them
3. Create two entries for each collection, filling only the title, and publish all 4 entities.
4. On one of the the entry of "test1", associate both entries of "test2" and publish this version
5. Edit again this entry of "test1", changing only the title, save and publish it
6. The server crashes with the following error :

```
[2024-01-04 17:35:17.792] http: POST /content-manager/collection-types/api::test1.test1/20/actions/publish (90 ms) 200
/home/xxx/git/yyy/node_modules/pg-protocol/dist/parser.js:287
        const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);
                                                                                                 ^

error: UPDATE "public"."test_2_s_test_1_s_links" as a
            SET "test_2_order" = b.inv_order
            FROM ( select "id", row_number() over (partition by "test_1_id" order by "test_2_order") as inv_order from "public"."test_2_s_test_1_s_links" where "test_1_id" in ($1) ) AS b
            WHERE b.id = a.id - interblocage (deadlock) détecté
    at Parser.parseErrorMessage (/home/xxx/git/yyy/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/xxx/git/yyy/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/xxx/git/yyy/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/xxx/git/yyy/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 447,
  severity: 'ERREUR',
  code: '40P01',
  detail: 'Le processus 15612 attend ShareLock sur transaction 5025 ; bloqué par le processus 10180.\n' +
    'Le processus 10180 attend ShareLock sur transaction 5023 ; bloqué par le processus 15612.',
  hint: 'Voir les journaux applicatifs du serveur pour les détails sur la requête.',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'lors de la mise à jour de la ligne (0,59) dans la relation « test_2_s_test_1_s_links »',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'deadlock.c',
  line: '1152',
  routine: 'DeadLockReport'
}
```

### Expected behavior

I expected the new version of test1 entry to be published, without the server crashing 😃 .

### Screenshots

![image](https://github.com/notum-cz/strapi-plugin-content-versioning/assets/35224301/f00a61a4-78d1-452a-b32d-56a2f22c0f03)

Just after the entity is published, the server crashes with the error above.
Yet, when I restart the server I see that the entity has been successfully published.

### System

- Node.js version: v18
- NPM version: 9.6.7
- Strapi version: 4.16.2
- Database: postgresql 14
- Operating system: WSL

### Additional context

I see in this issue https://github.com/notum-cz/strapi-plugin-content-versioning/issues/132 that you are currently working on supporting relations, so I don't know if my problem is a known limitation of this plugin or not

**Comment by omikulcik** [comment]
Hi @rtaieb, thank you for reporting this issue. I will try to reproduce it and get back to you. I do not think it is related to #132 because your example does not contain dynamic zones or components.

**Comment by omikulcik** [comment]
I have just tested it and it works fine for me. Do you have any other plugins installed that might be causing this please? 

![image](https://github.com/notum-cz/strapi-plugin-content-versioning/assets/44231035/ed6ce0bf-548b-4e99-ad3f-eddc64a87173)

**Comment by rtaieb** [comment]
Hi,
Thanks for having a look at it.
No, I did a fresh strapi install, I've installed only your plugin, and I got this issue.
Below is my package.json file : 
```
{
  "name": "testrt",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@notum-cz/strapi-plugin-content-versioning": "^1.2.8",
    "@strapi/plugin-cloud": "4.16.2",
    "@strapi/plugin-i18n": "4.16.2",
    "@strapi/plugin-users-permissions": "4.16.2",
    "@strapi/strapi": "4.16.2",
    "pg": "8.8.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "5.3.4",
    "styled-components": "5.3.3"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "xxx-xxx-xxxxx-xxx"
  },
  "engines": {
    "node": ">=18.0.0 <=20.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

I had the same error when I deployed my real project version (so with more other plugins) on my paas (scalingo), also when using postgres.
Should I try with another db ?

**Comment by omikulcik** [comment]
Thank you for more details. I am also using dockerized Postgres. I will try to replicate this one more time on a completely fresh install and see whether the bug occurs.  Previously I have tested it in a folder where I do other things but the same version of Strapi and the plugin is installed there so I do not think it will be different

**Comment by hassan-debug** [comment]
I am Faced Same issue today working with ManyToMany RelationShip 
Further more i also noticed that when we write a new version many to Many relation of previous version dropped
here is the example I have a **Post** collection with manytoMany relationShip with **Category** 

When i create Version1 of my content i added category **NBA** to V1 and then published it
<img width="1261" alt="Screenshot 2024-01-09 at 8 03 52 pm" src="https://github.com/notum-cz/strapi-plugin-content-versioning/assets/66749023/2c9fbd19-ded3-448a-a264-f37894574536">

then i made 2 more versions of my post below is V3 the latest update i made .. i published it and then i decided to unpublish v3 and i publish V1 
<img width="1277" alt="Screenshot 2024-01-09 at 8 06 23 pm" src="https://github.com/notum-cz/strapi-plugin-content-versioning/assets/66749023/5f63e53f-045e-4d65-96d3-5e5fca1a7d25">


<img width="1277" alt="Screenshot 2024-01-09 at 8 00 25 pm" src="https://github.com/notum-cz/strapi-plugin-content-versioning/assets/66749023/dcc09148-0e58-4f4c-88ef-8fa93b9ec0cc">

what i realize when i publish v3 then category relation with v1 and v2 is dropped 
so when i publish v1 category relation was missing in V1 and V2

**Comment by omikulcik** [comment]
Hi guys, I have tried to replicate this on a fresh install of Strapi and the same error occured. I will examine why this might be happening.

<img width="907" alt="image" src="https://github.com/notum-cz/strapi-plugin-content-versioning/assets/44231035/388ca843-dad5-450f-a54b-f4872ed75bf8">

**Comment by omikulcik** [comment]
Strangely, just switching the forEach loop with for loop solved it for me. I have merged the PR and will publish a new version. Please test if it is solved also for you.
