### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by giacomo-porro** [notum-cz/strapi-plugin-content-versioning#165]
Hi everyone, thanks for the work you're putting into this :)

I noticed that there is a condition in which the versioning plugin breaks while upgrading from version 0.4.11 to 1.2.8 ( but this is the same also with version 1.0.1 )

I created a zip file containing the Strapi test project that I used to reproduce the issue, you can find it in attachment.

Basically, if you create a model that has both versioning and i18n active, when I try to create a new record using REST APIs, I get the error below
```
TypeError: Cannot read properties of undefined (reading 'length')
    at Object.create (/Users/giacomo.porro/test-version-plugin/node_modules/@notum-cz/strapi-plugin-content-versioning/server/services/entity-service-decorator.js:102:43)
    at Object.create (/Users/giacomo.porro/test-version-plugin/node_modules/@strapi/plugin-i18n/server/services/entity-service-decorator.js:130:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.create (/Users/giacomo.porro/test-version-plugin/node_modules/@strapi/strapi/dist/core-api/controller/collection-type.js:46:22)
    at async returnBodyMiddleware (/Users/giacomo.porro/test-version-plugin/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:42:18)
    at async policiesMiddleware (/Users/giacomo.porro/test-version-plugin/node_modules/@strapi/strapi/dist/services/server/policy.js:15:5)
    at async /Users/giacomo.porro/test-version-plugin/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:27:12
    at async /Users/giacomo.porro/test-version-plugin/node_modules/@strapi/strapi/dist/middlewares/body.js:45:9
    at async /Users/giacomo.porro/test-version-plugin/node_modules/@strapi/strapi/dist/middlewares/powered-by.js:9:5
    at async cors (/Users/giacomo.porro/test-version-plugin/node_modules/@koa/cors/index.js:61:32)
```

### Steps to reproduce the behavior

1. Unzip the file [test-version-plugin.zip](https://github.com/notum-cz/strapi-plugin-content-versioning/files/13874419/test-version-plugin.zip)
2. run yarn develop ( or npm run develop )
3. launch this cURL
```
curl --location 'http://localhost:1337/api/test-versionings' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer 7b4fec12a10090c6d1878b65c724b5f100e4f530a081ccd61a6464006b153f13c29101b653dafc9833518b7ee64439b5d9209ad6f2a7b401c6ba9a79503434eac1acdd30bf141b4bafd3b3a87722b80c12a81dcf7ffd1d24cfc78aaafcb87f397c50b9c6505cae5a453d9e55a5abdedf6807e3cd8d793ade764b07e363ca0834' \
--data '{
    "data": {
        "test": "test"
    }
}'
```
5. See error

### Screenshots

<img width="828" alt="Screenshot 2024-01-09 at 14 58 15" src="https://github.com/notum-cz/strapi-plugin-content-versioning/assets/46812785/6835a747-7ce6-465d-8917-0f3bc08c6c83">

### Expected behavior

A new record is created in Strapi

### System

- Node.js version: 20.10.0
- NPM version: 10.2.3
- Strapi version: 4.16.2
- Database: SQLLite
- Operating system: MacOS Sonoma 14.2.1

### Additional context

Maybe it's worth noting that if I add "localizations": [] to the above JSON body everything works fine
```
curl --location 'http://localhost:1337/api/test-versionings' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer 7b4fec12a10090c6d1878b65c724b5f100e4f530a081ccd61a6464006b153f13c29101b653dafc9833518b7ee64439b5d9209ad6f2a7b401c6ba9a79503434eac1acdd30bf141b4bafd3b3a87722b80c12a81dcf7ffd1d24cfc78aaafcb87f397c50b9c6505cae5a453d9e55a5abdedf6807e3cd8d793ade764b07e363ca0834' \
--data '{
    "data": {
        "test": "test",
        "localizations": []
    }
}'
```

**Comment by giacomo-porro** [comment]
Oh, btw, I think this problem was already reported here https://github.com/notum-cz/strapi-plugin-content-versioning/issues/152 but I am not using the GQL plugin whatsoever

**Comment by omikulcik** [comment]
Hi @giacomo-porro, thank you for reporting this issue with a thorough description. It seems  that optional chaining could solve this issue. I will test it :)

**Comment by omikulcik** [comment]
Yup, that was it. This fix will be shipped in the next version this week.

**Comment by giacomo-porro** [comment]
Wow, super quick! Thanks a lot!
