### ISSUE TITLE
ManyToMany Relation dropped for all versions when we mark publish any version

### ISSUE THREAD

**Issue by hassan-debug** [notum-cz/strapi-plugin-content-versioning#166]
Create content collection and category collection and both have manyToMany relation with eachOther
create v1 of content and assign 1-2 categories  to v1 of a content 
then write v2 and v3 of same content
then publish v3 
then again publish v1
you will notice that 1-2 categories that you assign in v1 are missing now

**Comment by omikulcik** [comment]
Hi @hassan-debug, thank you for reporting this issue. I believe it might be happening for the same reason as #164 so I will try to solve it first.

**Comment by omikulcik** [comment]
Additional fix was needed. Hopefully it wont break any other use cases. It is hard to think of all of the possible combinations of relations
