### ISSUE TITLE
Single Type White Page 

### ISSUE THREAD

**Issue by adamrpostjr** [notum-cz/strapi-plugin-content-versioning#177]
## Bug report
White Page when Versioning is turned on for single type
### Describe the bug
When editing a single type on the latest version of strapi, the page is all white and the error message in the console is: 
main.0c57bcbc.js:2444 RangeError: Invalid time value
![image](https://github.com/notum-cz/strapi-plugin-content-versioning/assets/32047648/20ef3177-5439-4540-b72b-0c1b755962da)

When I disable versioning, everything is fine. 

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 18.18
- Yarn version:  1.22.19
- Strapi version: 4.19.1
- Database: MariaDB
- Operating system: Windows/Rocky 8

**Comment by navneetset** [comment]
Can further confirm, same issue for us as well.

**Comment by millsoft** [comment]
Can confirm on latest version of Strapi.

**Comment by edgardz** [comment]
Same here. 

- Node.js version: 18.19
- NPM version: 10.2.3
- Strapi version: 4.20.1
- Database: MySQL

**Comment by alexzhangreslv** [comment]
I have submitted a pull request #189 to fix this issue. This issue occurs since Strapi v4.17.1 where `isCreatingEntry` will always be false and thus this line `{format(parseISO(initialData.createdAt), "MMM d, yyyy HH:mm")}` will always be triggered even if `initialData` is empty.
