### ISSUE TITLE
latest version of content versioning does not work with strapi 4.1.5

### ISSUE THREAD

**Issue by jordanvector** [notum-cz/strapi-plugin-content-versioning#18]
## Bug report

Build fails with publisher plugin enabled on latest strapi version 4.1.5

### Describe the bug

npm run build --clean

build fails with this error

`ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/design-system/Text' in '/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/admin/src/components/Versions'
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/webpack/lib/Compilation.js:2011:28
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/neo-async/async.js:6883:13
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/webpack/lib/NormalModuleFactory.js:955:45
    at finishWithoutResolve (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '@strapi/design-system/Text' in '/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/admin/src/components/Versions'
  Parsed request is a module
  using description file: /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/package.json (relative path: ./admin/src/components/Versions)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/admin/src/components/Versions/node_modules doesn't exist or is not a directory
      /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/admin/src/components/node_modules doesn't exist or is not a directory
      /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/admin/src/node_modules doesn't exist or is not a directory
      /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/admin/node_modules doesn't exist or is not a directory
      looking for modules in /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/node_modules
        /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/node_modules/@strapi/design-system doesn't exist
      /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/node_modules doesn't exist or is not a directory
      /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules
        existing directory /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/design-system
          using description file: /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/design-system/package.json (relative path: .)
            using description file: /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/design-system/package.json (relative path: ./Text)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/design-system/Text doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/design-system/Text.js doesn't exist
              .jsx
                Field 'browser' doesn't contain a valid alias configuration
                /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/design-system/Text.jsx doesn't exist
              .react.js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/design-system/Text.react.js doesn't exist
              as directory
                /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/design-system/Text doesn't exist
      /Users/jordanschinella/Sites/connectedfitness/node_modules doesn't exist or is not a directory
      /Users/jordanschinella/Sites/node_modules doesn't exist or is not a directory
      /Users/jordanschinella/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/admin/node_modules
        /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/admin/node_modules/@strapi/design-system doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/design-system/Text' in '/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/admin/src/components/Versions'
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/webpack/lib/Compilation.js:2011:28
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/neo-async/async.js:6883:13
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/webpack/lib/NormalModuleFactory.js:955:45
    at finishWithoutResolve (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '@strapi/design-system/Text' in '/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/admin/src/components/Versions'
  Parsed request is a module
  using description file: /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/package.json (relative path: ./admin/src/components/Versions)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/admin/src/components/Versions/node_modules doesn't exist or is not a directory
      /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/admin/src/components/node_modules doesn't exist or is not a directory
      /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/admin/src/node_modules doesn't exist or is not a directory
      /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/admin/node_modules doesn't exist or is not a directory
      looking for modules in /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/node_modules
        /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/node_modules/@strapi/design-system doesn't exist
      /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/node_modules doesn't exist or is not a directory
      /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules
        existing directory /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/design-system
          using description file: /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/design-system/package.json (relative path: .)
            using description file: /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/design-system/package.json (relative path: ./Text)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/design-system/Text doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/design-system/Text.js doesn't exist
              .jsx
                Field 'browser' doesn't contain a valid alias configuration
                /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/design-system/Text.jsx doesn't exist
              .react.js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/design-system/Text.react.js doesn't exist
              as directory
                /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/design-system/Text doesn't exist
      /Users/jordanschinella/Sites/connectedfitness/node_modules doesn't exist or is not a directory
      /Users/jordanschinella/Sites/node_modules doesn't exist or is not a directory
      /Users/jordanschinella/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/admin/node_modules
        /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/admin/node_modules/@strapi/design-system doesn't exist
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi@0.1.0 build: `strapi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jordanschinella/.npm/_logs/2022-03-18T15_24_23_631Z-debug.log`

### Steps to reproduce the behavior

npm run build --clean

### Expected behavior

build completes successfully

### System

- Node.js version: v14 or v16
- NPM version: 6.0.0
- Strapi version: 4.1.5
- Database: mysql
- Operating system: alpine based container also fails with debian based container

**Comment by martincapek** [comment]
Hi, thanks for report. We will publish new version today so it should be fixed.

**Comment by martincapek** [comment]
fixed in v0.4.0

**Comment by jordanvector** [comment]
@martincapek confirmed, this is good to go now.  Thanks for the quick fix!
