### ISSUE TITLE
Access versioned content via API

### ISSUE THREAD

**Issue by dsosborn** [notum-cz/strapi-plugin-content-versioning#23]
I was eventually able to successfully install this plugin by reverting to Strapi 4.0.2, however I'm not able to access any of the alternate version content in the API? Is it expected that we should be able to, or is the intent of this plugin only to be able to access the multiple versions within the Strapi admin interface?

**Comment by martincapek** [comment]
Hi, other versions are accessible as drafts in strapi https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/filtering-locale-publication.html#filtering. So you can access it like this. Right now we are not planning to add custom REST for versioned content.

**Comment by omikulcik** [comment]
Closing this issue as it is inactive and has been answered.
