### ISSUE TITLE
Patch outdated

### ISSUE THREAD

**Issue by SoftCreatR** [notum-cz/strapi-plugin-content-versioning#24]
I just installed this plugin in 4.1.9. However, the patch is for 4.0.2. Here's an updated version of the patch.

[@strapi+admin+4.1.9.patch.txt](https://github.com/notum-cz/strapi-plugin-content-versioning/files/8599759/%40strapi%2Badmin%2B4.1.9.patch.txt)

**Comment by rweintraub-cycleon** [comment]
for those that are already on 4.1.11 this patch works as well if you just rename it.
thanks @SoftCreatR !

**Comment by martincapek** [comment]
Added to folder thanks!
