### ISSUE TITLE
We'd love if the save button automatically created a new version. If you make changes on a version then hit the save button, the changes you had previous are lost. When you hit the save button it should also create a new version

### ISSUE THREAD

**Issue by alexkess101** [notum-cz/strapi-plugin-content-versioning#29]

**Comment by martincapek** [comment]
Hi, you can apply patch so it will override save button, patch update for new strapi will be released in few days. Also we are currently working to override it automatically without need to patch it.

**Comment by martincapek** [comment]
I hope it will be uploaded tomorrow. With updated documentation.

**Comment by martincapek** [comment]
Hi, patches are uploaded in last commit, please see README section Override Save Button.
