### ISSUE TITLE
content-versioning plugin ain't working in prod

### ISSUE THREAD

**Issue by triiivedi-rapipay** [notum-cz/strapi-plugin-content-versioning#30]
I have been trying to work with content versioning plugin for so long but even after installing the plugin and enabling it in the plugins.js it is not working or not showing any changes in content-type as before creating the collection-type or single-type we have to enable content-versioning just like i18n but that option is not available there, but when I open up the watch-admin mode I get to see that enable content versioning option and it is working fine in watch-admin mode.

**Comment by martincapek** [comment]
Hi, did you run `npm run build` ?
