### ISSUE TITLE
Prevent saving a new version when user cancels confirmation dialog 

### ISSUE THREAD

**Issue by ridoo** [notum-cz/strapi-plugin-content-versioning#32]
Making changes to content and clicking "save as new version" without saving beforehand will cause the plugin to falsely create a new version when user clicks cancel on the confirmation dialog.

**Comment by martincapek** [comment]
Hi, we are right now working on new way of saving versions. But I will look at it.

**Comment by omikulcik** [comment]
There is no "save as new version" button in the new version so I am closing this.
