### ISSUE TITLE
Is there a way to access the version data from the api? 

### ISSUE THREAD

**Issue by alexkess101** [notum-cz/strapi-plugin-content-versioning#33]
We are trying to implement a preview button for the latest version. We's love to be able to access the data of the versions from the api. For example,

`localhost:1337/articles?versions=all` 

And this would return all of the versions? Does something like this exist?

**Comment by martincapek** [comment]
Hi, we are using draft/publish from strapi, so you can change your endpoint to return all draft versions, we dont want to add versions=all since you want have some versions private and URL parameters are pretty simple to fake it.

**Comment by alexkess101** [comment]
So will the draft version give me the most recent saved version? Also, are there any examples of a request like that?

**Comment by alexkess101** [comment]
I'm realizing my original comment might have been a bit hard to understand. What we're trying to do is be able to access the different versions on a single article. Let's there is an article where version 8 is published. However there is a change that we  have been iterating over where we are currently on version 12. Published version is version 8 and the highest version we're on is version 12. 

What we want is to be able to preview that version 12 even though version 8 will still be the page in production. If we could get access to all of the versions for each article then we could create a plugin that shows the preview of the page according to it's most recent version and not it's published version.

How is this possible?

**Comment by martincapek** [comment]
Hi, we are create preview option in one of our project that generate UUID for version and then open it on UUID not version id. I can send you some snippets if it's still problem for you.

**Comment by alexkess101** [comment]
Yeah, if you could sent some snippets that would be awesom!

**Comment by ninayujiri** [comment]
Hi @martincapek, would you be able to provide me the same code snippets? I am also trying to make the versioning work with previews.

**Comment by martincapek** [comment]
@ninayujiri  Hi, I will send these snippets here in this issue, so everyone can see it! :)

**Comment by KempfCreative** [comment]
I would also be interested in these snippets please @martincapek

**Comment by palbrecht1** [comment]
Same @martincapek :p

**Comment by Fikoun** [comment]
@alexkess101 Answer to your problem should be in previous comment where by providing query options like 
`?populate=versions&publicationState=preview` you can fetch all entities with related versions populated.
I have a feature ready with better handling of the 'newest/published' version, also adding optional flag `versions=all` (as you suggested). Could be ready and merged by next week.

**Comment by omikulcik** [comment]
I am closing this as it is solved. Will add it do the readme.
