### ISSUE TITLE
On save/publish how to create new version automatically if new changes made? Currently, we need to click on save a new version button.

### ISSUE THREAD

**Issue by Risheekesh** [notum-cz/strapi-plugin-content-versioning#34]
Screenshot: 

![image](https://user-images.githubusercontent.com/11422844/177140328-e684ce89-58e1-46b6-8f47-3d77bb3686a6.png)

**Comment by martincapek** [comment]
You can use patch package to create new version on save button. It is here in readme https://github.com/notum-cz/strapi-plugin-content-versioning#-override-save-button-optional
