### ISSUE TITLE
Missing 'moment' dependency as of Strapi v4.3.0

### ISSUE THREAD

**Issue by rlouAU** [notum-cz/strapi-plugin-content-versioning#35]
### Describe the bug

When running `npm install` on a project with this plugin and strapi v4.3.0+, I receive the following Error:

ModuleNotFoundError: Module not found: Error: Can't resolve 'moment' in '/opt/node_modules/@notum-cz/strapi-plugin-content-versioning/admin/src/components/Versions'

### Steps to reproduce the behavior

1. Have a strapi app with this plugin and strapi version 4.3.0
2. Run `npm i`
3. See error

### Expected behavior

Strapi app should install successfully.

### System

- Node.js version: v14
- NPM version: v6
- Strapi version: v4.3.2
- Database: MySQL v5.7.38
- Operating system: Windows 10

### Additional context

It seems like strapi removed their 'moment' dependency as of PR [#13728](https://github.com/strapi/strapi/pull/13728).

**Comment by Tikondra** [comment]
<img width="288" alt="image" src="https://user-images.githubusercontent.com/52007300/184656603-2ee42321-fe5e-408e-a551-dbcd848db84d.png">
