### ISSUE TITLE
Content-Versioning Not Working Properly with Strapi v4.3.2

### ISSUE THREAD

**Issue by pandeyprafull** [notum-cz/strapi-plugin-content-versioning#37]
### Describe the bug
Content-versioning behave abnormal with Strapi **v4.3.2**

### Steps to reproduce the behavior

Step 1: - Create a Content and save.
Step 2: - Modify some changes in content and `save as new version`.
Step 3: - You will get a an alert prompt that you will lost your changes.
Step 4: - Reload the page and then you will get your new version content in the dropdown. 

### Expected behavior

Rather than It should prompt a green message that you have successfully made your changes. Previously it was working with strapi **v4.0.3**

### Screenshots
![issue](https://user-images.githubusercontent.com/29433163/184884049-7ab74547-08ba-412d-b625-088c5c1a6174.png)
![Screenshot from 2022-08-16 18-10-41](https://user-images.githubusercontent.com/29433163/184884064-0b640384-7c07-4ea6-9658-42486b65b58f.png)

### Code snippets
Plugin Configuration
```
    "content-versioning": {
        enabled: true,
    },
```

### System

- Node.js version: v14.18.1
- NPM version: 8.3.0
- Strapi version: 4.3.2
- Database: Mysql
- Operating system: Ubuntu

**Comment by pandeyprafull** [comment]
[derrickmehaffy](https://github.com/derrickmehaffy) please help ...

**Comment by pandeyprafull** [comment]
@martincapek I applied the patch for auto version while save the content but getting another issue of showing error as patch is available for strapi V4.0.3 and my current strapi version is 4.3.2

**Comment by martincapek** [comment]
Hi @pandeyprafull in https://github.com/notum-cz/strapi-plugin-content-versioning/tree/main/patches are patches for more versions of strapi, just take a looks and download your version please.

**Comment by Fikoun** [comment]
> I applied the patch for auto version while save the content but getting another issue of showing error as patch is available for strapi V4.0.3 and my current strapi version is 4.3.2

@pandeyprafull,
Have you also rebuild your strapi project, which is necessary after code change.
