### ISSUE TITLE
Create new patch for newer version of strapi

### ISSUE THREAD

**Issue by martincapek** [notum-cz/strapi-plugin-content-versioning#38]
Create new version of patch for newer version of strapi. Current patch is outdated.

**Comment by martincapek** [comment]
Fixes #37

**Comment by adedoyin-paystack** [comment]
@martincapek  There is yet another version of Strapi -> 4.3.6
And now the patch has started throwing the error again.

**Comment by aeadedoyin** [comment]
@martincapek There is yet another version of Strapi -> 4.3.6
And now the patch has started throwing the error again.
