### ISSUE TITLE
Module doesn't appear in Strapi 4.3.8

### ISSUE THREAD

**Issue by tutunci** [notum-cz/strapi-plugin-content-versioning#44]
Hi,
I've installed your module on the last Strapi 4.3.8 version , unfortunately, the module doesn't appear in the catalog.
Reading the first step is about "Versioning must be enabled in settings of Content Type. Same as localization plugin."
Unfortunately, I didn't see any flag in the popup of Advanced settings.
Is there any workaround I can do setting a row in the db or config file in order to enable first step?

Moreover the patch is not available for 4.3.8, I've renamed 4.3.6 version, is it ok?

Thanks
Maurizio

**Comment by martincapek** [comment]
Hi! Did you rebuild strapi `npm run build` and add plugin to `config/plugins.js`?

**Comment by tutunci** [comment]
Hi,
yes I've restarted in develop mode and put into the pulgins.js this code

  'content-versioning': {
        enabled: true,
        debug: true,
  },

Is it enough to see the module?

Thanks 
Maurizio

**Comment by martincapek** [comment]
@tutunci yes, should be just this. And renaming patch is also okey

**Comment by tutunci** [comment]
Did you have any trick to check about the module, something DB side or code side adding some logs?

**Comment by olivier1208** [comment]
You need to rebuild your **admin**
`npm run build` or `yarn build`

**Comment by hevar** [comment]
Currently have the same issue, Strapi v. `4.5.0`.

Added:

```
"content-versioning": {
    enabled: true,
    debug: true,
  },
  
```

Have ran ´yarn build´ numerous times. Without any luck.

**Comment by olivier1208** [comment]
@hevar 
Be also sure to fulfill all the requirements listed in the README

https://github.com/notum-cz/strapi-plugin-content-versioning#%EF%B8%8F-read-before-installation

> Versioning must be enabled in settings of Content Type. Same as localization plugin.
You need to have enabled draft/publish system on your content type.
Roles that are going to use the plugin need to have permission enabled in the Settings > Roles > ... > Plugins view.
You need to create/modify file config/plugins.js with
