### ISSUE TITLE
Incorrect sql query in core-api.js

### ISSUE THREAD

**Issue by dmitrynjg** [notum-cz/strapi-plugin-content-versioning#45]
### Hello 👋

The original query was
`INSERT INTO ${model.collectionName}_versions_links VALUES (${version},${result.id})` and I had a problem creating a new version I kept getting a 500 error from the server, eventually changing query to node_modules/@notum-cz/strapi-plugin-content-versioning/server/services/core-api.js for `INSERT INTO ${model.collectionName}_versions_links (post_id, inv_post_id) VALUES (${version}, ${result.id})` helped.

**Comment by lundcm** [comment]
Yeah, this seems strange. I was running into an issue with the same area of code. I removed the entire for loop and it seems to work just fine. I don't understand why it would need to insert every version on every new version.

```javascript
    for (const version of data.versions) {
      await strapi.db.connection.raw(
        `INSERT INTO ${model.collectionName}_versions_links VALUES (${version},${result.id})`
      );
    }
```
