### ISSUE TITLE
Version List : only versions lower than the showed display can be seen

### ISSUE THREAD

**Issue by luan-bird** [notum-cz/strapi-plugin-content-versioning#46]
Strapi Version : 4.3.8
content-versioning-plugin Version: 0.4.4

![image](https://user-images.githubusercontent.com/105047093/192405229-eeff6290-bbe5-40fc-b7b9-74a372707bcd.png)

when I change showed version to 3 only see version (1/2)

![image](https://user-images.githubusercontent.com/105047093/192405335-609aa705-25f2-4f36-90c1-f139d8521859.png)

Thanks for your help !

**Comment by RicardoCruzXID** [comment]
This issue will be fixed when PR #48 is applied and  #merged

**Comment by luan-bird** [comment]
Thanks @RicardoCruzXID , it worked.
But there is one other little problem，  when the content-type name contains ‘-' e.g: 'type-demo' , it will give error.
` error: INSERT INTO type_demos_versions_links (type-demo_id, inv_type-demo_id) VALUES (1,2) - syntax error at or near "-"
error: INSERT INTO type_demos_versions_links (type-demo_id, inv_type-demo_id) VALUES (1,2) - syntax error at or near "-"
`
