### ISSUE TITLE
Internal server while Saving new version

### ISSUE THREAD

**Issue by john-smartenovations** [notum-cz/strapi-plugin-content-versioning#50]
### Describe the bug

Internal server while Saving new version

### Steps to reproduce the behavior

1. Go to Content Manager
2. Click on Save New Version
3. Internal server error is thrown
4. In terminal SQL error was shown "INSERT INTO test_versions_versions_links VALUES (29,30) - ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1"

### Expected behavior

Should save the new version

### Screenshots

![image](https://user-images.githubusercontent.com/63772696/196467909-2102ae7d-75ea-41bb-9cd4-6d2c76ec9a05.png)

### System

- Node.js version: v16.15.0
- NPM version: 8.5.5
- Strapi version: 4.3.8
- Database: MySQL
- Operating system: Windows

**Comment by obogz** [comment]
I get the same:
I have unique fields and if I try to save it I get this
{"data":null,"error":{"status":400,"name":"ValidationError","message":"2 errors occurred","details":{"errors":[{"path":["linkId"],"message":"This attribute must be unique","name":"ValidationError"},{"path":["link"],"message":"This attribute must be unique","name":"ValidationError"}]}}}

**Comment by obogz** [comment]
I think I found my answer
![image](https://user-images.githubusercontent.com/5851247/196566169-08d913e0-ef3c-4394-a8f8-803c46c2bd25.png)

**Comment by hansoncyu** [comment]
I'm getting the same error without using any unique fields. This is after I upgraded my strapi version to 4.4.3. Existing versioned content types continue to work but newly created types on the new strapi version will cause versioning to break.
To reproduce, use a newish strapi version, create a new content type with versioning enabled and one simple text field. Create a new entry on the type and then try to create a new version

**Comment by zenkevin** [comment]
Same problem here as @hansoncyu using the same steps on a fresh install of strapi v4.4.5

**Comment by tasola** [comment]
Same here with v4.4.6 and v4.4.7...

**Comment by tasola** [comment]
This solves the issue for me: https://github.com/notum-cz/strapi-plugin-content-versioning/pull/52

**Comment by martincapek** [comment]
Fixed https://github.com/notum-cz/strapi-plugin-content-versioning/pull/52
