### ISSUE TITLE
The latest patch for 4.5.0 cannot be applied to Strapi 4.5.4

### ISSUE THREAD

**Issue by mjadczuk** [notum-cz/strapi-plugin-content-versioning#57]
## Bug report

The latest patch file in the repository [`@strapi+admin+4.5.0.patch`](https://github.com/notum-cz/strapi-plugin-content-versioning/blob/main/patches/%40strapi%2Badmin%2B4.5.0.patch) fails with an error when running `patch-package` on Strapi 4.5.4.

### Steps to reproduce the behavior

1. Install Strapi 4.5.4.
2. Add the patch file for 4.5.0 to `patches/`.
3. Run `patch-package`.

### Expected behavior

Patch is applied without any errors or warnings.

### Actual behavior

```
$ patch-package
patch-package 6.5.0
Applying patches...

**ERROR** Failed to apply patch for package @strapi/admin at path
  
    node_modules/@strapi/admin

  This error was caused because patch-package cannot apply the following patch file:

    patches/@strapi+admin+4.5.4.patch

  Try removing node_modules and trying again. If that doesn't work, maybe there was
  an accidental change made to the patch file? Try recreating it by manually
  editing the appropriate files and running:
  
    patch-package @strapi/admin
  
  If that doesn't work, then it's a bug in patch-package, so please submit a bug
  report. Thanks!

    https://github.com/ds300/patch-package/issues
    

---
patch-package finished with 1 error(s).
```

### System

- Node.js version: v16
- Strapi version: 4.5.4

### Additional context

Downgrading to Strapi 4.5.3 allows to run the patch without any errors.

**Comment by markhughes** [comment]
I have created a patch here and submitted a PR

https://github.com/markhughes/strapi-plugin-content-versioning/blob/7e06fda94f70753b0edb96e5be698cc824959d8f/patches/%40strapi%2Badmin%2B4.5.4.patch
