### ISSUE TITLE
Not working with strapi v4.6.2

### ISSUE THREAD

**Issue by DanielGardiner** [notum-cz/strapi-plugin-content-versioning#70]
## Bug report

This plugin does not work when updating to strapi v4.6.2

### Describe the bug

After updating to strapi v4.6.2 publishing content doesn't work. When I click 'Publish' it saves a new blank version of the content and the original content is still in draft.

This might be due to the fact that `axiosInstance` has now been deprecated..?

### Steps to reproduce the behavior

1. Update strapi to v4.6.2
2. Either create some new content or edit existing content which is version controlled
3. Click 'Save', everything works as expected
4. Click 'Publish' a blank new item of content is created
5. Navigate back to the content dashboard and you'll see the original content we were trying publish remains in draft, and additional a new blank item of content is created which is also in draft

### Expected behavior

The original content is published

**Comment by omikulcik** [comment]
Hello @DanielGardiner, I have taken over the maintenance of this plugin. Unfortunately, the #72 doesn't solve the support for 4.6.2 to a full extent so it will not be merged. We are now working on fixing the patch problem entirely in the next milestone.

**Comment by omikulcik** [comment]
The patch problem has been solved so I am closing this.
