### ISSUE TITLE
Deactivating and Activating the plugin causes corruption in the database

### ISSUE THREAD

**Issue by thewickest** [notum-cz/strapi-plugin-content-versioning#71]
### Describe the bug

I have an issue regarding the way the plugin version the entities with its internal identifier. I was testing it in some branch, and I change to other branch where the plugin was not activated yet because it was in a older version of the project.I found that the entities that where versioned were now in the admin panel like 'normal' entities. I changed again to the branch with the plugin (with the `enabled: true` attribute inside the plugin.js) and now the entities that were versioned are not acting like versioned anymore. I check the database and the `vuid` that seems to identify the group of entities is empty so there is no way to identify those entities that were versioned before.

### Steps to reproduce the behavior
To reproduce the error: 
1. Go to the plugin.js of your project and deactivate the plugin
2. Reload Strapi
3. Check that the entities that where versioned before are not versioned anymore.
4. Activate the plugin again.

### Expected behavior

It should maintain the previous state of the application in case you accidentally change to some branch or part of your project that does not have the plugin yet or you deactivated for some reason.

![image](https://user-images.githubusercontent.com/99754651/221622724-abc3f0a4-bbbb-4d01-812c-63e264855145.png)

In the picture, the ones with `vuid` are currently working and were added after I deactivated/activated the plugin. The ones that don't have vuid are added before I deactivated/activated the plugin.

### System

- Node.js version: 16.19.0
- NPM version: 8.19.3
- Strapi version: 4.6.1
- Database: MariaDB
- Operating system: MacOs Ventura 13.0.1

**Comment by Fikoun** [comment]
Hello @thewickest, thanks for writing detailed bug report.

We were dealing with this problem and it can be caused by using newest version of **Versioning plugin** with old data structure. For this, migrate your data manually, because the the versioning system is quite different.
Also most of our testing was done on Strapi Admin UI, so actions like disabling/enabling plugin were tested primary there.
If you still experience this problem on newer version of the plugin, let me know I will try to replicate this 1:1.

**Comment by thewickest** [comment]
Hi @Fikoun,

Yes I'm using the latest version of the plugin, but I don't know about the old data structure. It is a test project because we want to include it on a bigger project so it could a problem if we start versioning data and then we have to migrate it manually if something fails. What about some option to automatically save the structure of the database to retrieve the data in case something fails?

**Comment by Fikoun** [comment]
Im sorry but for now, we do not support this. Also working with plugin on the admin UI level you should get the warning about data loss, when disabling versioning on content type.

<img width="410" alt="Screenshot 2023-03-02 at 10 14 35" src="https://user-images.githubusercontent.com/20205140/222385347-1c155e1e-c101-45d5-8272-cf04d4d737eb.png">

**Comment by Fikoun** [comment]
@thewickest If this answered your problem, please react on this message.

**Comment by thewickest** [comment]
> @thewickest If this answered your problem, please react on this message.

Yes, it answer to my problem. I will take it into account. Thank you very much.
