### ISSUE TITLE
Patch version for 4.10.5 is needed

### ISSUE THREAD

**Issue by rootux** [notum-cz/strapi-plugin-content-versioning#85]
### Describe the bug

I'm getting this error when trying to use the patch methods:
    Patch file: patches/@strapi+admin+4.1.12.patch
    Patch was made for version: 4.1.12
    Installed version: 4.10.5

**Comment by omikulcik** [comment]
Hi @rootux thank you for submitting the issue. We are currently working on publishing a new version in which the path problem will be solved.

**Comment by NmN03jain** [comment]
can i work on this

**Comment by NmN03jain** [comment]
@omikulcik  Can pls more elaborate the issue, where I need to make changes ?

**Comment by omikulcik** [comment]
@NmN03jain The package @strapi/admin changes with each version and sometimes the changes are so significant that our patch does not work anymore. So the process is to install Strapi at 4.10.5, install our plugin and try editing /node_modules/@strapi/admin/admin/src/content-manager/components/CollectionTypeFormWrapper/index.js and 
/node_modules/@strapi/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js

the way the plugin works. You can get inspired in patches for the other versions. Then create the patch using patch-package.

**Comment by gaurab-keen** [comment]
I am getting null in after Enable vesion comment and save

**Comment by omikulcik** [comment]
Hello, we have just released a new version which removes the need for a patch so I am closing this.

**Comment by rootux** [comment]
Amazing.. Thank you
