### ISSUE TITLE
Duplicate entries when saving as a new version

### ISSUE THREAD

**Issue by RickardssonJ** [notum-cz/strapi-plugin-content-versioning#87]
### Describe the bug

When clicking on the save as a new version button, a new version is created but not "on top" of the old one. The button creates a duplicated version of the old entry, resulting in two different entries but with version number 1.

If I then update the new entry (supposed to be version 2) and click save as a new version the result is as expected. A new version is created "on top" of the old one.
At least that's what it looks like in the _main_ entry list. But if I set a filter on the list _title -> is not null_ i can see a new duplicate on version 2.

### Steps to reproduce the behavior

1. Go to Content Manager.
2. Chose a  collection type and click "+ Create new entry"
3. Fill in some data. Click save.
4. Make some changes in the data and click on "save as a new version"

### Expected behavior

I Expect the version 1 entry to be removed from the collection types entries list and replaced with the new version (Version 2 )

### Screenshots
<img width="1011" alt="Skärmavbild 2023-05-31 kl  16 11 37" src="https://github.com/notum-cz/strapi-plugin-content-versioning/assets/48394514/93031e2d-833a-4782-bd0a-9266015c37de">
(this is the result after creating a new entry and editing its data and saving it to a new version)

<img width="1014" alt="Skärmavbild 2023-05-31 kl  16 13 14" src="https://github.com/notum-cz/strapi-plugin-content-versioning/assets/48394514/3a70ecf3-8538-4643-8c07-2cdbf77bbfdf">
(this is after doing the exact same thing but on the newly created update)

<img width="998" alt="Skärmavbild 2023-05-31 kl  16 14 47" src="https://github.com/notum-cz/strapi-plugin-content-versioning/assets/48394514/3bb80bed-e72a-46c1-8cf1-6e2a5478065e">
(And this is with the filter applied)

### System

- Node.js version: v16.15.0
- NPM version: 8.5.5
- Strapi version: 4.4.0
- Database: postgres
- Operating system: MacOS Monterey v.12.5 Apple M1 Pro
- strapi-plugin-content-versioning: 1.0.0-beta.0

**Comment by omikulcik** [comment]
Hi @RickardssonJ, thank you for reporting this bug. I will try to replicate this.

**Comment by RickardssonJ** [comment]
Thank you @omikulcik 

Any luck with this?

**Comment by omikulcik** [comment]
@RickardssonJ Yes, I was successful replicating it. I believe it is the same problem as mentioned in #75. Please have a look as there is a hotfix/patch proposed.

**Comment by omikulcik** [comment]
Solved in #94
