### ISSUE TITLE
Locales is saved as there own versions.

### ISSUE THREAD

**Issue by RickardssonJ** [notum-cz/strapi-plugin-content-versioning#94]
### Describe the bug

When clicking the native Strapi save button that is now overridden as the save as a new version button. A new version is created (as expected) but that makes it so that when you want to translate content in a new locale and you have to click the save button to save for example the English translation. That will create a version only for the English translation with its own unique UUID and then when you translate that content to a new locale, for example, to Spanish it will create a new version with the Spanish translation and a new unique UUID only for the Spanish translation.

### Steps to reproduce the behavior

1. Go to Content Manager.
2. Chose a collection type and click "+ Create new entry"
3. Fill in some text. Click save.
4. Change the locale and fill in the translation for the text.
5. Click save

### Expected behavior
When clicking save I want the content to be saved as a draft so that I can fill in different translations (locales) and also save them in a draft. Then when the entire entry is ready with all its translations I want to save it as one combined version.

### System

- Node.js version: v16.15.0
- NPM version: 8.5.5
- Strapi version: 4.4.0 and 4.6.0
- Database: postgres
- Operating system: MacOS Monterey v.12.5 Apple M1 Pro
- strapi-plugin-content-versioning: 0.4.7

This is a side effect of the fix for this bug:
https://github.com/notum-cz/strapi-plugin-content-versioning/issues/87

And with this patch:
[@notum-cz+strapi-plugin-content-versioning+0.4.7.patch](https://github.com/notum-cz/strapi-plugin-content-versioning/files/11362031/%40notum-cz%2Bstrapi-plugin-content-versioning%2B0.4.7.patch)

**Comment by omikulcik** [comment]
Hello @RickardssonJ, I believe this is not a bug but the plugin is meant to work this way. As far as I am concerned, the plugin has never had a feature to save as a one combined version as you mention.

**Comment by RickardssonJ** [comment]
Ah i see thank you @omikulcik
